-- CC-136 Part A — answer_history archive table.
--
-- One row per `resetSessionAnswer` call. Append-only snapshot of the
-- prior live answer + timestamp + reason. Cascade-deletes when the
-- underlying session is deleted; orphaned history is meaningless.
--
-- Note: this migration was generated by `drizzle-kit generate` against
-- a schema state that retroactively included the existing
-- `follow_up_links` table (its 0006 hand-authored migration was not
-- snapshotted into meta). The auto-emitted duplicate `follow_up_links`
-- statements have been STRIPPED here — only the genuinely new
-- `answer_history` statements remain. The `0007_snapshot.json` correctly
-- captures both tables and is left as-is so future migrations diff from
-- the right baseline.

CREATE TABLE "answer_history" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"session_id" uuid NOT NULL,
	"question_id" text NOT NULL,
	"answer" jsonb NOT NULL,
	"archived_at" timestamp with time zone DEFAULT now() NOT NULL,
	"reason" text DEFAULT 'admin_reset' NOT NULL
);
--> statement-breakpoint
ALTER TABLE "answer_history" ADD CONSTRAINT "answer_history_session_id_sessions_id_fk" FOREIGN KEY ("session_id") REFERENCES "public"."sessions"("id") ON DELETE cascade ON UPDATE no action;
