// CC-HANDS-CARD baseline snapshot — captures the rendered card sections
// of the 8 existing body cards BEFORE the Hands card is wired in. Run
// once pre-CC; the audit (#13) reads this file and compares.
//
// This file is generated by `npx tsx tests/audit/handsCardBaseline.snapshot.ts`
// and writes to `tests/audit/handsCardBaseline.snapshot.json`. Do not
// hand-edit the JSON.

import { createHash } from "node:crypto";
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { buildInnerConstitution } from "../../lib/identityEngine";
import { renderMirrorAsMarkdown } from "../../lib/renderMirror";
import type { Answer, DemographicSet } from "../../lib/types";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const ROOT = join(__dirname, "..", "fixtures");
const OUT = join(__dirname, "handsCardBaseline.snapshot.json");

const CARD_HEADERS = [
  "### Lens — Eyes",
  "### Compass — Heart",
  "### Trust — Ears",
  "### Gravity — Spine",
  "### Conviction — Voice",
  "### Weather — Nervous System",
  "### Fire — Immune Response",
];

function extractSection(md: string, header: string): string | null {
  const idx = md.indexOf(header);
  if (idx < 0) return null;
  // Section runs until the next "###" header at the same depth.
  const rest = md.slice(idx);
  const nextHeader = rest.slice(header.length).search(/\n### /);
  if (nextHeader < 0) return rest.trimEnd();
  return rest.slice(0, header.length + nextHeader).trimEnd();
}

function hash(s: string): string {
  return createHash("sha256").update(s).digest("hex").slice(0, 16);
}

function snapshot(): void {
  const out: Record<string, Record<string, string>> = {};
  for (const dir of ["ocean", "goal-soul-give"]) {
    for (const f of readdirSync(join(ROOT, dir))
      .filter((x) => x.endsWith(".json"))
      .sort()) {
      const key = `${dir}/${f}`;
      const raw = JSON.parse(readFileSync(join(ROOT, dir, f), "utf-8")) as {
        answers: Answer[];
        demographics?: DemographicSet | null;
      };
      const c = buildInnerConstitution(raw.answers, [], raw.demographics ?? null);
      const md = renderMirrorAsMarkdown({
        constitution: c,
        includeBeliefAnchor: false,
      });
      out[key] = {};
      for (const header of CARD_HEADERS) {
        const section = extractSection(md, header);
        out[key][header] = section ? hash(section) : "(missing)";
      }
    }
  }
  writeFileSync(OUT, JSON.stringify(out, null, 2));
  console.log(`Snapshot written to ${OUT} for ${Object.keys(out).length} fixtures`);
}

snapshot();
